<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Fornecedor
                    <a href="<?php echo $this->url('fornecedor') . '/cadastro'?>" type="button" class="btn btn-success fa fa-plus pull-right"> Novo Fornecedor</a>
                    <div class="col-md-3 input-group pesquisa custom-search-form">
                        <input type="text" class="form-control" placeholder="Pesquisa...">
                        <span class="input-group-btn">
                            <button class="btn btn-default text-right" title="Pesquisar" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                            
                        </span>
                    </div>
                    
                </h1>
                
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Nome</th>
                            <th>Last Name</th>
                            <th>Username</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <th>
                                <a class="cursor" data-toggle="modal" data-target="#fornecedorModel"><span class="fa fa-fw fa-2x fa-edit" title="Editar"></span></a>
                                <a class="cursor" onclick="deletar_fornecedor();"><span class="fa fa-fw fa-2x fa-trash" title="Excluir"></span></a>
                            </th>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Jacob</td>
                            <td>Thornton</td>
                            <td>@fat</td>
                             <th>
                                <a href=""><span class="fa fa-fw fa-2x fa-edit" title="Editar"></span></a>
                                <a href=""><span class="fa fa-fw fa-2x fa-trash" title="Excluir"></span></a>
                            </th>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Larry</td>
                            <td>the Bird</td>
                            <td>@twitter</td>
                             <th>
                                <a href=""><span class="fa fa-fw fa-2x fa-edit" title="Editar"></span></a>
                                <a href=""><span class="fa fa-fw fa-2x fa-trash" title="Excluir"></span></a>
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div> 
    </div>
</div>  
<script>
    function deletar_fornecedor(){
        swal({
            title: "Are you sure?",
            text: "You will not be able to recover this imaginary file!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: false,
            closeOnCancel: false
        },
        function(isConfirm){
            if (isConfirm) {
              swal("Deleted!", "Your imaginary file has been deleted.", "success");
            } else {
              swal("Cancelled", "Your imaginary file is safe :)", "error");
            }
        });
    }

</script>



  
    

